<?php
define( 'WC_JIBIT_ORDER_INITIAL', 'INITIAL' );
define( 'WC_JIBIT_ORDER_PGENTRY', 'PGENTRY' );
define( 'WC_JIBIT_ORDER_CANCEL_BY_SYSTEM', 'CANCEL_BY_SYSTEM' );
define( 'WC_JIBIT_ORDER_CANCEL_BY_USER', 'CANCEL_BY_USER' );
define( 'WC_JIBIT_ORDER_PURCHASE_BY_USER', 'PURCHASE_BY_USER' );
define( 'WC_JIBIT_ORDER_PURCHASE_CONFIRM_BY_MERCHANT', 'PURCHASE_CONFIRM_BY_MERCHANT' );
